#!/bin/bash
set -e

echo "=== THA Tennis Points Platform - 部署指南 ==="
echo ""
echo "本项目使用 Render（后端 + PostgreSQL）+ Vercel（前端）免费部署。"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "步骤 1: 部署后端到 Render"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. 将代码推送到 GitHub 仓库"
echo "2. 访问 https://render.com 注册/登录"
echo "3. 点击 'New' → 'Blueprint'"
echo "4. 连接你的 GitHub 仓库"
echo "5. Render 会自动读取 render.yaml 创建服务和数据库"
echo "6. 等待部署完成，记录后端 URL（如 https://tha-tennis-api.onrender.com）"
echo ""
echo "部署完成后初始化数据："
echo "  在 Render Dashboard → tha-tennis-api → Shell 中执行："
echo "  cd backend && uv run python -m app.scripts.seed_full"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "步骤 2: 部署前端到 Vercel"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "用户端 H5："
echo "  1. 访问 https://vercel.com 注册/登录"
echo "  2. Import Git Repository → 选择你的仓库"
echo "  3. Root Directory 设为: frontend/user"
echo "  4. Framework Preset: Vite"
echo "  5. 添加环境变量:"
echo "     VITE_API_BASE_URL = https://tha-tennis-api.onrender.com/api/v1"
echo "  6. Deploy"
echo ""
echo "管理端："
echo "  1. 再次 Import 同一仓库（Vercel 支持同仓库多项目）"
echo "  2. Root Directory 设为: frontend/admin"
echo "  3. Framework Preset: Vite"
echo "  4. 添加环境变量:"
echo "     VITE_API_BASE_URL = https://tha-tennis-api.onrender.com/api/v1"
echo "  5. Deploy"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "步骤 3: 验证"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  后端健康检查: curl https://tha-tennis-api.onrender.com/api/v1/health"
echo "  用户端: https://tha-tennis-user.vercel.app"
echo "  管理端: https://tha-tennis-admin.vercel.app"
echo "  登录账号: admin / admin123"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "注意事项"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  - Render 免费版冷启动约 30 秒（15 分钟无请求后休眠）"
echo "  - Render 免费 PostgreSQL 90 天后过期，需重新创建"
echo "  - Vercel 免费版无限制，适合前端托管"
echo "  - 后端 URL 中的 'tha-tennis-api' 取决于你的 Render 服务名"
echo ""
